# -*- coding: utf-8 -*-
"""
Deduplicated peptide dataset for the Peptides 4 Power Reconstitution Guide eBook.

Source: P4P_Cheat_Sheet.pdf (Official Peptide Dosing Reference Guide).
Every peptide appears exactly once. Where a peptide was listed in multiple
categories on the cheat sheet (e.g. MOTS-C, KPV, Epitalon, GHK-Cu), the most
complete row was kept and the duplicate dropped.

Each entry:
  category : section the peptide belongs to
  name     : peptide name (unique key)
  rows     : list of (vial_size, bac_water, units_to_draw) reconstitution rows
  freq     : injection frequency
  dose     : dose per injection
  note     : timing / stacking / handling tip
  cycle    : how long to run it
  purpose  : primary benefits ( " . " separated )
  admin    : administration route (default "Subcutaneous injection")
"""

SUBQ = "Subcutaneous injection"
IM = "Intramuscular injection"

PEPTIDES = [
    # ===================== GH & MUSCLE SUPPORT =====================
    dict(category="GH & Muscle Support", name="CJC-1295 (with DAC)",
         rows=[("2mg", "1ml", "25u"), ("5mg", "2ml", "20u")],
         freq="M / W / F", dose="500mcg",
         note="Longer-acting than No-DAC; provides a steadier GH elevation rather than a natural pulse.",
         cycle="8-12 weeks on, 8 off", purpose="Muscle . Fat loss . Anti-aging . GH"),
    dict(category="GH & Muscle Support", name="CJC-1295 (No DAC)",
         rows=[("2mg", "2ml", "15-30u"), ("5mg", "2.5ml", "7-15u"), ("10mg", "2.5ml", "4-8u")],
         freq="2-3x daily, fasted", dose="150-300mcg",
         note="Short half-life - time doses around fasted windows for a cleaner GH pulse.",
         cycle="8-12 weeks on, 8 off", purpose="Muscle . Fat loss . Anti-aging . GH"),
    dict(category="GH & Muscle Support", name="Ipamorelin",
         rows=[("2mg", "2ml", "15-30u"), ("5mg", "2.5ml", "7-15u"), ("10mg", "2.5ml", "4-8u")],
         freq="2-3x daily, fasted", dose="150-300mcg",
         note="Clean, selective GH release with minimal cortisol or prolactin spike. Pairs perfectly with CJC-1295.",
         cycle="8-12 weeks on, 8 off", purpose="Fat loss . Increased GH . Recovery . Sleep"),
    dict(category="GH & Muscle Support", name="CJC / Ipamorelin Blend",
         rows=[("5mg / 5mg", "2ml", "15-30u"), ("10mg / 10mg", "2ml", "7-15u")],
         freq="2-3x daily, fasted", dose="150-300mcg",
         note="Dose exactly as you would Ipamorelin. The blend pairs a GHRH (CJC) with a GHRP (Ipa) for synergy.",
         cycle="8-12 weeks on, 8 off", purpose="Fat loss . Increased GH . Recovery"),
    dict(category="GH & Muscle Support", name="Tesamorelin",
         rows=[("10mg", "2ml", "20-40u"), ("20mg", "2ml", "10-20u")],
         freq="Daily, PM fasted", dose="1-2mg",
         note="Inject PM on an empty stomach. Best known for targeting visceral (belly) fat.",
         cycle="10-16 weeks", purpose="Belly fat . Low LDL . Cognitive . GH"),
    dict(category="GH & Muscle Support", name="Sermorelin",
         rows=[("5mg", "2ml", "10-20u"), ("10mg", "2ml", "5-10u")],
         freq="Daily PM, fasted", dose="250-500mcg",
         note="Can be stacked with GHRP-2 or Ipamorelin to amplify the GH pulse.",
         cycle="Up to 6 months", purpose="Muscle . Fat . Anti-aging . GH . Sleep"),
    dict(category="GH & Muscle Support", name="Tesa / IPA Blend",
         rows=[("10mg / 3mg", "2ml", "10-20u")],
         freq="Daily PM, fasted", dose="500mcg / 150mcg",
         note="Inject PM fasted. Combines Tesamorelin's visceral-fat action with Ipamorelin's clean pulse.",
         cycle="10-16 weeks", purpose="GH . Fat loss . Muscle"),
    dict(category="GH & Muscle Support", name="IGF-1 LR3",
         rows=[("1mg", "1.5ml BAC + 0.5ml Acetic", "10-20u")],
         freq="AM, after workout", dose="50-100mcg",
         note="Reconstitute with bacteriostatic water plus acetic acid. Eat carbohydrates right after dosing.",
         cycle="10 days - 6 weeks", purpose="Muscle growth . Recovery . Bone", admin=IM),
    dict(category="GH & Muscle Support", name="PEG-MGF",
         rows=[("2mg", "2ml", "10u (per side)")],
         freq="3-4x / week, post-workout", dose="100mcg each side",
         note="Injected intramuscularly and bilaterally - each arm, leg or shoulder you are training.",
         cycle="4-8 weeks", purpose="Muscle growth . Recovery . Bone", admin=IM),
    dict(category="GH & Muscle Support", name="MGF",
         rows=[("2mg", "1ml", "10u"), ("5mg", "2ml", "8u"), ("10mg", "3ml", "6u")],
         freq="Daily, post-workout", dose="200mcg",
         note="Injected intramuscularly into each muscle group trained (arm, leg, shoulder).",
         cycle="4-8 weeks", purpose="Muscle growth . Local repair", admin=IM),
    dict(category="GH & Muscle Support", name="Follistatin 344",
         rows=[("1mg", "2ml", "20u")],
         freq="Daily", dose="100mcg",
         note="SubQ or IM, dosed bilaterally. Reconstitute with acetic acid if it will not dissolve.",
         cycle="10-30 days", purpose="Muscle growth . Myostatin support"),
    dict(category="GH & Muscle Support", name="GHRP-2",
         rows=[("5mg", "2.5ml", "10-13u")],
         freq="2x daily M-F, fasted", dose="200-250mcg",
         note="Take fasted. Strong GH release - may transiently raise appetite, cortisol and prolactin.",
         cycle="8-12 weeks", purpose="GH . Fat loss . Muscle . Sleep . Skin"),
    dict(category="GH & Muscle Support", name="ACE-031",
         rows=[("1mg", "2ml", "20u")],
         freq="Every other day", dose="1mg",
         note="Run on a simple every-other-day (EOD) protocol.",
         cycle="4-8 weeks", purpose="Muscle growth . Bone density"),
    dict(category="GH & Muscle Support", name="MOTS-C",
         rows=[("10mg", "1ml", "50-100u"), ("20mg", "2ml", "50-100u"), ("40mg", "3ml", "50-100u")],
         freq="1-3x per week", dose="5-10mg",
         note="Best used AFTER an SS-31 protocol to prime the mitochondria.",
         cycle="8-10 weeks", purpose="Performance . Fat loss . Mitochondrial"),

    # ===================== HEALING & RECOVERY =====================
    dict(category="Healing & Recovery", name="BPC-157",
         rows=[("5mg", "2ml", "10u"), ("10mg", "3ml", "8u")],
         freq="2-3x daily", dose="250-270mcg (up to 1000mcg/day)",
         note="Excellent for gut health and systemic inflammation. Can be injected near the injury site.",
         cycle="8 weeks on, 8 off", purpose="Tissue repair . Tendons . Gut . Collagen"),
    dict(category="Healing & Recovery", name="TB-500",
         rows=[("5mg", "3ml", "20u"), ("10mg", "3ml", "15u")],
         freq="Daily", dose="500mcg (up to 1000mcg/day)",
         note="Anti-inflammatory and improves flexibility. Loads daily, then tapers to a maintenance dose.",
         cycle="8 weeks on, 8 off", purpose="Tissue repair . Healing . Endurance"),
    dict(category="Healing & Recovery", name="BPC / TB-500 Blend",
         rows=[("5mg / 5mg", "2ml", "10u"), ("10mg / 10mg", "2ml", "8u")],
         freq="2-3x daily", dose="250mcg each",
         note="The classic synergistic healing stack - systemic repair plus local tendon and tissue recovery.",
         cycle="8 weeks on, 8 off", purpose="Tissue repair . Tendons . Healing"),
    dict(category="Healing & Recovery", name="GLOW (BPC / TB / GHK-Cu)",
         rows=[("10 / 10 / 70mg", "3ml", "10-15u")],
         freq="Daily", dose="500mcg / 500mcg / 3500mcg",
         note="Do not dose higher than the listed amounts. A complete recovery and skin-rejuvenation blend.",
         cycle="8 weeks on, 8 off", purpose="Healing . Recovery . Anti-aging . Skin"),
    dict(category="Healing & Recovery", name="KLOW (BPC / TB / GHK-Cu / KPV)",
         rows=[("10 / 10 / 50 / 10mg", "3ml", "15u")],
         freq="Daily", dose="500 / 500mcg / 2.5mg / 500mcg",
         note="Do not dose higher. KLOW adds KPV to GLOW for extra anti-inflammatory and gut support.",
         cycle="8 weeks on, 8 off", purpose="Healing . Recovery . Anti-aging . Inflammation"),
    dict(category="Healing & Recovery", name="KPV",
         rows=[("10mg", "2ml", "10-20u"), ("30mg", "3ml", "10-20u")],
         freq="M-F", dose="500mcg - 1mg",
         note="Avoid NSAIDs while running it; reconstitute with acetic acid if the peptide gels.",
         cycle="8 weeks on, 8 off", purpose="Anti-inflammatory . Gut health"),

    # ===================== FAT LOSS & METABOLISM =====================
    dict(category="Fat Loss & Metabolism", name="Retatrutide",
         rows=[("10mg", "2ml", "20u"), ("20mg", "2ml", "10u"), ("30mg", "3ml", "10u")],
         freq="2x per week", dose="1mg (titrate up to 10mg)",
         note="Start low; add roughly 2mg every 4 weeks. A triple-agonist (GLP-1 / GIP / glucagon).",
         cycle="Until results met", purpose="Fat loss . Liver fat . Insulin sensitivity"),
    dict(category="Fat Loss & Metabolism", name="Tirzepatide",
         rows=[("15mg", "2ml", "10-20u"), ("30mg", "3ml", "10-20u"), ("60mg", "4ml", "10-20u")],
         freq="Weekly or 2x per week", dose="0.5-2mg (titrate up)",
         note="Start low and titrate slowly to manage GI side effects. A dual GLP-1 / GIP agonist.",
         cycle="Until results met", purpose="Fat loss . Appetite suppression . Metabolic"),
    dict(category="Fat Loss & Metabolism", name="Cagrilintide",
         rows=[("5mg", "2ml", "10-80u"), ("10mg", "3ml", "7-60u")],
         freq="Weekly or 2x per week", dose="0.25-2mg",
         note="Works well stacked with a GLP-1. Start low and build up gradually.",
         cycle="Up to 16 weeks", purpose="Appetite suppression . Fat loss"),
    dict(category="Fat Loss & Metabolism", name="AOD-9604",
         rows=[("5mg", "1.5ml BAC + 0.5ml Acetic", "12-20u")],
         freq="Daily AM", dose="300-500mcg",
         note="Reconstitute with ~1.6ml BAC water and 0.4ml acetic acid. A fragment of GH for fat loss only.",
         cycle="Ongoing", purpose="Fat loss . Metabolism"),
    dict(category="Fat Loss & Metabolism", name="5-Amino 1MQ",
         rows=[("10mg", "1ml", "10-20u"), ("50mg", "3ml", "10-20u")],
         freq="Daily", dose="250-500mcg",
         note="An NNMT inhibitor that supports metabolic rate and fat-cell turnover.",
         cycle="Ongoing", purpose="Fat loss . Metabolic function"),
    dict(category="Fat Loss & Metabolism", name="AICAR",
         rows=[("50mg", "2ml", "20-50u")],
         freq="3-5x per week", dose="1-2mg",
         note="An AMPK activator - mimics aspects of exercise for fat oxidation.",
         cycle="8-12 weeks", purpose="Fat oxidation . Metabolic health"),
    dict(category="Fat Loss & Metabolism", name="Adipotide",
         rows=[("10mg", "2ml", "10-20u")],
         freq="Daily", dose="500mcg - 1mg",
         note="Targets the blood supply (vasculature) feeding fat cells for localized reduction.",
         cycle="4-8 weeks", purpose="Fat loss . Targeted fat reduction"),
    dict(category="Fat Loss & Metabolism", name="SLU-PP-332",
         rows=[("5mg", "1ml", "10-60u")],
         freq="Up to 3x daily", dose="500mcg - 3mg",
         note="May require DMSO or saline to fully reconstitute. An exercise-mimetic for fat oxidation.",
         cycle="Ongoing", purpose="Fat oxidation . Energy . Recovery"),
    dict(category="Fat Loss & Metabolism", name="Eloralintide",
         rows=[("10mg", "2ml", "10-20u")],
         freq="Weekly", dose="0.5-1mg",
         note="A novel amylin-based weight-management peptide.",
         cycle="Up to 16 weeks", purpose="Weight management . Metabolic support"),

    # ===================== LONGEVITY & MITOCHONDRIAL =====================
    dict(category="Longevity & Mitochondrial", name="FOXO4-DRI",
         rows=[("5mg", "1ml", "60u"), ("10mg", "1ml", "50u"), ("10mg", "2ml", "20u")],
         freq="EOD (Opt 1) / 5 on, 5 off (Opt 2)", dose="3-5mg (Opt 1) . 1mg (Opt 2)",
         note="Option 1: EOD ongoing. Option 2: 5 days on / 5 off, ~1 month total, up to 2x per year. A senolytic.",
         cycle="Ongoing or 2 weeks, 2x/year", purpose="Senolytic . Anti-aging . Cellular cleanup"),
    dict(category="Longevity & Mitochondrial", name="Epitalon",
         rows=[("10mg", "1ml", "50-100u"), ("50mg", "3ml", "30-60u")],
         freq="Daily PM", dose="5-10mg",
         note="Often stacked with Vilon or Livagen. Supports telomere length and circadian rhythm.",
         cycle="2-3 weeks, 2x/year", purpose="Anti-aging . Telomeres . Sleep . Immune"),
    dict(category="Longevity & Mitochondrial", name="NA-Epitalon",
         rows=[("20mg", "2ml", "20-40u")],
         freq="Daily PM", dose="2-4mg",
         note="An N-acetylated version of Epitalon with enhanced bioavailability.",
         cycle="2-3 weeks, 2x/year", purpose="Anti-aging . Telomeres"),
    dict(category="Longevity & Mitochondrial", name="SS-31",
         rows=[("10mg", "1ml", "10-20u"), ("30mg", "2ml", "10-20u"), ("50mg", "3ml", "10-20u")],
         freq="Daily", dose="1-3mg",
         note="A mitochondria-targeted peptide; strong cardioprotective research profile.",
         cycle="8-12 weeks", purpose="Mitochondrial protection . Cardioprotection"),
    dict(category="Longevity & Mitochondrial", name="NAD+ Buffered",
         rows=[("500mg", "2ml", "50-100u")],
         freq="Daily or as needed", dose="250-500mg",
         note="Inject slowly. Central to cellular energy production and DNA repair.",
         cycle="Ongoing", purpose="Cellular energy . DNA repair . Anti-aging"),
    dict(category="Longevity & Mitochondrial", name="Humanin",
         rows=[("10mg", "1ml", "50-100u")],
         freq="Daily", dose="5-10mg",
         note="A mitochondrial-derived peptide studied for neuroprotection and metabolic health.",
         cycle="8-10 weeks", purpose="Neuroprotection . Metabolic health"),
    dict(category="Longevity & Mitochondrial", name="Mito-Prime (5-Amino / MOTS-C / NAD+)",
         rows=[("120mg", "2ml", "20-50u")],
         freq="Daily", dose="1-3mg",
         note="A comprehensive mitochondrial blend combining three energy-support compounds.",
         cycle="8-10 weeks", purpose="Energy . Fat loss . Longevity"),

    # ===================== COGNITIVE & MOOD =====================
    dict(category="Cognitive & Mood", name="Selank",
         rows=[("10mg", "3ml", "6-10u")],
         freq="Daily AM", dose="200-330mcg",
         note="Anxiolytic and nootropic. Often used in the morning for calm focus.",
         cycle="8 weeks on, 8 off", purpose="Anxiety . Cognitive . Memory . Mood"),
    dict(category="Cognitive & Mood", name="NA-Selank",
         rows=[("10mg", "3ml", "6-10u")],
         freq="Daily AM", dose="200-330mcg",
         note="An N-acetylated, longer-acting version of Selank.",
         cycle="8 weeks on, 8 off", purpose="Anxiety . Cognitive . Memory . Mood"),
    dict(category="Cognitive & Mood", name="Semax",
         rows=[("10mg", "3ml", "6-10u")],
         freq="Daily AM", dose="200-330mcg",
         note="A nootropic that supports BDNF, focus and neuroprotection.",
         cycle="8 weeks on, 8 off", purpose="Cognitive . Memory . Neuroprotection"),
    dict(category="Cognitive & Mood", name="NA-Semax",
         rows=[("10mg", "3ml", "6-10u")],
         freq="Daily AM", dose="200-330mcg",
         note="An N-acetylated, enhanced version of Semax.",
         cycle="8 weeks on, 8 off", purpose="Cognitive . Memory . Neuroprotection"),
    dict(category="Cognitive & Mood", name="Adamax",
         rows=[("10mg", "2ml", "10-20u")],
         freq="Daily", dose="300mcg - 1mg",
         note="A nootropic peptide for focus, learning and neuroprotection.",
         cycle="Up to 15 weeks", purpose="Cognitive enhancement . Focus . Neuroprotection"),
    dict(category="Cognitive & Mood", name="Adamax w/ Adamantane",
         rows=[("10mg", "2ml", "10-20u")],
         freq="Daily AM", dose="500mcg - 1mg",
         note="The adamantane-enhanced version of Adamax for stronger, longer cognitive effect.",
         cycle="8 weeks on, 8 off", purpose="Cognitive enhancement . Focus . Neuroprotection"),
    dict(category="Cognitive & Mood", name="Cerebrolysin",
         rows=[("30mg", "2ml", "20-50u")],
         freq="Daily", dose="2-5mg",
         note="A neuroregenerative peptide mixture supporting brain recovery and cognition.",
         cycle="4-8 weeks", purpose="Neuroregeneration . Cognitive function"),
    dict(category="Cognitive & Mood", name="PE-22-28",
         rows=[("10mg", "2ml", "8-30u")],
         freq="Daily", dose="250mcg - 1mg",
         note="A fast-acting antidepressant peptide (a spadin analog).",
         cycle="8-12 weeks", purpose="Cognitive . Antidepressant . Focus"),
    dict(category="Cognitive & Mood", name="P-21",
         rows=[("10mg", "2ml", "10-20u")],
         freq="Daily", dose="500mcg - 1mg",
         note="Supports neuroplasticity and new neuron formation (neurogenesis).",
         cycle="8-12 weeks", purpose="Cognitive . Neuroplasticity . Memory"),
    dict(category="Cognitive & Mood", name="Oxytocin",
         rows=[("5mg", "2ml", "10-20u"), ("10mg", "2ml", "5-10u")],
         freq="As needed", dose="250-500mcg",
         note="The bonding hormone - used situationally for mood and social connection.",
         cycle="As needed", purpose="Social connection . Mood . Stress relief"),
    dict(category="Cognitive & Mood", name="VIP",
         rows=[("5mg", "3ml", "6-18u")],
         freq="Daily", dose="100-300mcg",
         note="May cause transient flushing. Often used in CIRS / mold-recovery protocols.",
         cycle="8 weeks on, 8 off", purpose="Memory . Autoimmune . Blood flow"),

    # ===================== IMMUNITY & INFLAMMATION =====================
    dict(category="Immunity & Inflammation", name="Thymalin",
         rows=[("10mg", "1ml", "100u"), ("20mg", "2ml", "50u")],
         freq="Daily", dose="10mg / 5mg",
         note="Run as a short course 1-4 times per year to restore immune function.",
         cycle="10 days, 1-4x/year", purpose="Immunity restoration"),
    dict(category="Immunity & Inflammation", name="Thymosin Alpha-1",
         rows=[("10mg", "2ml", "10-20u")],
         freq="2x weekly", dose="500mcg - 1mg",
         note="A powerful immune modulator for viral defense and autoimmune balance.",
         cycle="8-12 weeks", purpose="Immunity . Viral defense . Autoimmune"),
    dict(category="Immunity & Inflammation", name="LL-37",
         rows=[("5mg", "3ml", "9u")],
         freq="2x daily AM / PM", dose="150mcg",
         note="Inject SubQ morning and evening. An antimicrobial peptide.",
         cycle="50 days on", purpose="Immunity . Anti-inflammation"),
    dict(category="Immunity & Inflammation", name="Glutathione",
         rows=[("600mg", "2ml", "20-50u"), ("1500mg", "3ml", "20-50u")],
         freq="2-3x weekly", dose="600-1500mg",
         note="The body's master antioxidant - supports liver, skin and immune health.",
         cycle="Ongoing", purpose="Antioxidant . Immune . Liver . Skin"),

    # ===================== HAIR, SKIN & COSMETIC =====================
    dict(category="Hair, Skin & Cosmetic", name="GHK-Cu",
         rows=[("50mg", "2ml", "10-20u"), ("100mg", "3ml", "8-15u")],
         freq="Daily", dose="2.5-5mg",
         note="The classic copper peptide for skin, hair and collagen synthesis.",
         cycle="8 weeks on, 8 off", purpose="Skin . Hair . Collagen . Anti-inflammatory"),
    dict(category="Hair, Skin & Cosmetic", name="AHK-Cu",
         rows=[("100mg", "3ml", "8u")],
         freq="Daily", dose="2.5mg",
         note="A copper peptide focused on hair growth and follicle health.",
         cycle="8 weeks on, 8 off", purpose="Hair growth . Skin repair . Anti-aging"),
    dict(category="Hair, Skin & Cosmetic", name="SNAP-8",
         rows=[("10mg", "2ml", "10-20u")],
         freq="Daily", dose="500mcg - 1mg",
         note="An anti-wrinkle peptide that softens expression lines.",
         cycle="8 weeks on, 8 off", purpose="Anti-wrinkle . Expression lines"),
    dict(category="Hair, Skin & Cosmetic", name="Melanotan I",
         rows=[("10mg", "2ml", "10u")],
         freq="2-3x weekly", dose="500mcg",
         note="A tanning peptide with a milder side-effect profile than MT-II.",
         cycle="30 days", purpose="Tan . UV protection"),
    dict(category="Hair, Skin & Cosmetic", name="Melanotan II",
         rows=[("10mg", "2ml", "10u")],
         freq="2-3x weekly", dose="500mcg",
         note="A potent tanning peptide that also influences libido and appetite.",
         cycle="30 days", purpose="Tan . Libido . Appetite suppression"),

    # ===================== AMINO BLENDS =====================
    dict(category="Amino Blends", name="L-Carnitine",
         rows=[("500-600mg/ml", "Premixed", "50-100u")],
         freq="Daily as needed", dose="250-600mg",
         note="Injected intramuscularly, ideally fasted before cardio.",
         cycle="Months", purpose="Body composition . Energy . Fat loss", admin=IM),
    dict(category="Amino Blends", name="Lipo-C MIC-B12",
         rows=[("Premixed", "N/A", "1ml")],
         freq="Daily as needed", dose="1ml",
         note="The classic lipotropic (MIC + B12) fat-mobilizing blend.",
         cycle="Ongoing", purpose="Fat mobilization . Energy"),
    dict(category="Amino Blends", name="Lipo-C Fat Blaster",
         rows=[("Premixed", "N/A", "1ml")],
         freq="Daily as needed", dose="1ml",
         note="An advanced lipotropic blend for accelerated fat loss.",
         cycle="Ongoing", purpose="Aggressive fat loss . Metabolic"),
    dict(category="Amino Blends", name="Lipo-C Super Shred",
         rows=[("Premixed", "N/A", "1ml")],
         freq="Daily as needed", dose="1ml",
         note="A maximum-strength lipotropic shredding blend.",
         cycle="Ongoing", purpose="Maximum fat shredding"),
    dict(category="Amino Blends", name="Lipo-C Super Human",
         rows=[("Premixed", "N/A", "1ml")],
         freq="Daily as needed", dose="1ml",
         note="A peak-performance lipotropic and energy blend.",
         cycle="Ongoing", purpose="Peak performance . Fat loss"),
    dict(category="Amino Blends", name="Lipo-B",
         rows=[("Premixed", "N/A", "1ml")],
         freq="Daily as needed", dose="1ml",
         note="A B-vitamin lipotropic shot for fat metabolism and energy.",
         cycle="Ongoing", purpose="Fat mobilization . Energy . B-vitamin support"),
    dict(category="Amino Blends", name="Lipo-C Focus",
         rows=[("Premixed", "N/A", "1ml")],
         freq="Daily as needed", dose="1ml",
         note="A lipotropic blend formulated for fat loss with added focus and energy.",
         cycle="Ongoing", purpose="Fat loss . Focus . Energy"),
    dict(category="Amino Blends", name="Lipo-C No B12",
         rows=[("Premixed", "N/A", "1ml")],
         freq="Daily as needed", dose="1ml",
         note="The classic lipotropic blend without B12, for those supplementing it separately.",
         cycle="Ongoing", purpose="Fat mobilization . Metabolic"),
    dict(category="Amino Blends", name="Lipo-C Super",
         rows=[("Premixed (10ml)", "N/A", "1ml")],
         freq="Daily as needed", dose="1ml",
         note="A higher-volume (10ml) lipotropic blend for extended fat-loss support.",
         cycle="Ongoing", purpose="Fat loss . Metabolic . Energy"),
    dict(category="Amino Blends", name="Lemon Bottle",
         rows=[("Premixed", "N/A", "1ml")],
         freq="As needed", dose="1ml",
         note="A fat-dissolving injection for localized, targeted areas.",
         cycle="As needed", purpose="Targeted fat reduction"),

    # ===================== BIOREGULATORS =====================
    dict(category="Bioregulators", name="Vilon",
         rows=[("20mg", "2ml", "25u")],
         freq="2x daily", dose="2.5mg",
         note="Pairs with Epitalon. A short bioregulator peptide for cellular health.",
         cycle="15-30 days", purpose="Neuroprotective . Mood . Focus"),
    dict(category="Bioregulators", name="Cardiogen",
         rows=[("20mg", "2ml", "10-40u")],
         freq="1-2x daily AM / PM", dose="1-4mg",
         note="A heart bioregulator supporting cardiac cell renewal.",
         cycle="30 days, 2x/year", purpose="Heart cell growth . Anti-tumor"),
    dict(category="Bioregulators", name="Bronchagen",
         rows=[("20mg", "2ml", "10-20u")],
         freq="1-2x daily AM / PM", dose="1-2mg",
         note="A lung bioregulator; can be combined with Chronluten.",
         cycle="30 days, 2x/year", purpose="Lung function . Inflammation . Asthma"),
    dict(category="Bioregulators", name="Prostamax",
         rows=[("20mg", "2ml", "10-50u")],
         freq="1-2x daily AM / PM", dose="5mg",
         note="A prostate bioregulator, also used for PCT support.",
         cycle="30 days, 2x/year", purpose="Prostate health . Anti-aging"),
    dict(category="Bioregulators", name="Testagen",
         rows=[("20mg", "2ml", "20u")],
         freq="1-2x daily AM / PM", dose="2mg",
         note="Supports natural testosterone; often used for PCT support.",
         cycle="10-30 days, 2x/year", purpose="Testosterone . Energy . Cognitive"),
    dict(category="Bioregulators", name="Ovagen",
         rows=[("20mg", "2ml", "20-50u")],
         freq="1-2x daily AM / PM", dose="2-5mg",
         note="A liver bioregulator supporting detox and metabolic function.",
         cycle="10-30 days, 2x/year", purpose="Liver inflammation . Metabolic"),
    dict(category="Bioregulators", name="Cartalax",
         rows=[("20mg", "2ml", "10-20u")],
         freq="1-2x daily AM / PM", dose="1-2mg",
         note="A cartilage bioregulator; inject near the target joint.",
         cycle="30 days, 1-3x/year", purpose="Joint . Cartilage regeneration"),
    dict(category="Bioregulators", name="Pinealon",
         rows=[("20mg", "2ml", "10-50u")],
         freq="1-2x daily AM / PM", dose="1-5mg",
         note="A brain bioregulator; pairs well with other cognitive peptides.",
         cycle="30 days, 1-3x/year", purpose="Cognitive . Brain health . Neuroprotection"),
    dict(category="Bioregulators", name="Vesugen",
         rows=[("20mg", "2ml", "20u")],
         freq="1-2x daily AM / PM", dose="2mg",
         note="A vascular bioregulator; pairs with Pinealon for nerve health.",
         cycle="30 days, 1-3x/year", purpose="Cognitive . Nerve health . Anti-aging"),
    dict(category="Bioregulators", name="Liveagen",
         rows=[("20mg", "2ml", "20-100u")],
         freq="1-2x daily AM / PM", dose="1-5mg",
         note="A liver / cellular bioregulator; pairs with Vilon or Epitalon.",
         cycle="15-30 days", purpose="Cellular regeneration . Immune"),
    dict(category="Bioregulators", name="Cortagen",
         rows=[("20mg", "2ml", "10-50u")],
         freq="1x daily", dose="1-5mg",
         note="A pancreas bioregulator supporting cellular repair.",
         cycle="30 days", purpose="Pancreas cell repair"),
    dict(category="Bioregulators", name="Pancragen",
         rows=[("20mg", "2ml", "20u")],
         freq="1x daily", dose="2mg",
         note="A pancreas bioregulator with immune support properties.",
         cycle="10-20 days", purpose="Immunity . Viral / bacterial defense"),
    dict(category="Bioregulators", name="Thymogen",
         rows=[("20mg", "2ml", "5-20u")],
         freq="1x daily", dose="500mcg - 2mg",
         note="An immune bioregulator - intramuscular administration only.",
         cycle="10-20 days", purpose="Immunity . Viral / bacterial defense", admin=IM),
    dict(category="Bioregulators", name="Crystagen",
         rows=[("20mg", "2ml", "20u")],
         freq="Daily", dose="2mg",
         note="An immunity and general-wellness bioregulator.",
         cycle="30 days", purpose="Immunity . Protein synthesis . Recovery"),
    dict(category="Bioregulators", name="Chronluten",
         rows=[("20mg", "2ml", "10-50u")],
         freq="1-2x daily AM / PM", dose="1-5mg",
         note="A respiratory bioregulator; can be used with Bronchagen.",
         cycle="30 days, 1-3x/year", purpose="Lung health"),
    dict(category="Bioregulators", name="Vesilute",
         rows=[("20mg", "2ml", "20u")],
         freq="1-2x daily AM / PM", dose="2mg",
         note="A vascular bioregulator supporting healthy blood flow.",
         cycle="30 days, 1-3x/year", purpose="Vascular health . Circulation"),

    # ===================== SEXUAL HEALTH =====================
    dict(category="Sexual Health", name="PT-141 (Bremelanotide)",
         rows=[("5mg", "2ml", "10-20u"), ("10mg", "2ml", "10-20u")],
         freq="As needed", dose="500mcg - 1mg",
         note="Inject on an empty stomach and avoid alcohol. Onset can take a few hours; "
              "use ahead of time, not immediately before.",
         cycle="As needed", purpose="Libido . Arousal . Sexual function"),
]


def validate_unique():
    names = [p["name"] for p in PEPTIDES]
    dupes = {n for n in names if names.count(n) > 1}
    assert not dupes, f"Duplicate peptides found: {dupes}"
    return len(names)


if __name__ == "__main__":
    n = validate_unique()
    cats = {}
    for p in PEPTIDES:
        cats.setdefault(p["category"], 0)
        cats[p["category"]] += 1
    print(f"{n} unique peptides across {len(cats)} categories:")
    for c, k in cats.items():
        print(f"  {k:>2}  {c}")
