/**
 * Peptide reference data — transcribed from the
 * "P4P AI Peptide Protocol Master Document" cheat sheet, reconstitution guide,
 * encyclopedia, and popular-stacks sections.
 *
 * FOR RESEARCH USE ONLY. Not medical advice. Not for human consumption.
 *
 * Numbers are used to pre-fill the reconstitution calculator. All values are
 * editable in the UI — the defaults simply reflect the document's guidance.
 */

export type StrengthUnit = "mg" | "iu";
export type DoseUnit = "mcg" | "mg" | "iu";

export type Solvent =
  | "BAC water"
  | "Acetic acid"
  | "BAC + Acetic acid"
  | "DMSO / Saline"
  | "Pre-mixed"
  | "None (oral)";

export interface Peptide {
  /** Display name */
  name: string;
  /** Category grouping used for filtering */
  category: PeptideCategory;
  /** Strength unit the vial is measured in (mg for most, iu for HGH/HCG) */
  strengthUnit: StrengthUnit;
  /** Common vial sizes (in `strengthUnit`) */
  vialSizes: number[];
  /** Suggested BAC water volume in ml for reconstitution (0 = no reconstitution) */
  defaultBacMl: number;
  /** Representative default dose value for the calculator */
  defaultDose: number;
  /** Unit for the default dose value */
  defaultDoseUnit: DoseUnit;
  /** Human-readable dose (as written in the cheat sheet) */
  doseText: string;
  frequency: string;
  route: string;
  cycle: string;
  purpose: string;
  solvent: Solvent;
  /** Reconstitution / handling caveats */
  notes?: string;
  /** Peptides this one is commonly stacked with */
  stacksWith?: string[];
  /** True for multi-peptide P4P blends (calculator treats vial size as total mg) */
  blend?: boolean;
}

export type PeptideCategory =
  | "GH & Muscle"
  | "Fat Loss & Metabolism"
  | "Healing & Recovery"
  | "Longevity & Mitochondrial"
  | "Cognitive & Mood"
  | "Immunity & Inflammation"
  | "Hair, Skin & Cosmetic"
  | "Sexual Health"
  | "Bioregulators";

export const CATEGORIES: PeptideCategory[] = [
  "GH & Muscle",
  "Fat Loss & Metabolism",
  "Healing & Recovery",
  "Longevity & Mitochondrial",
  "Cognitive & Mood",
  "Immunity & Inflammation",
  "Hair, Skin & Cosmetic",
  "Sexual Health",
  "Bioregulators",
];

export const PEPTIDES: Peptide[] = [
  // ---------------- GH & MUSCLE ----------------
  {
    name: "CJC-1295 (DAC)",
    category: "GH & Muscle",
    strengthUnit: "mg",
    vialSizes: [2, 5],
    defaultBacMl: 2,
    defaultDose: 500,
    defaultDoseUnit: "mcg",
    doseText: "500mcg",
    frequency: "M / W / F",
    route: "subQ",
    cycle: "8–12 wks, 8 off",
    purpose: "Muscle / Fat loss / Anti-age / GH",
    solvent: "BAC water",
    stacksWith: ["Ipamorelin"],
  },
  {
    name: "CJC-1295 (No DAC)",
    category: "GH & Muscle",
    strengthUnit: "mg",
    vialSizes: [2, 5, 10],
    defaultBacMl: 2,
    defaultDose: 200,
    defaultDoseUnit: "mcg",
    doseText: "150–300mcg",
    frequency: "2–3x daily, fasted",
    route: "subQ",
    cycle: "8–12 wks, 8 off",
    purpose: "Muscle / Fat loss / Anti-age / GH",
    solvent: "BAC water",
    notes: "Always pair with Ipamorelin (GHRH + GHRP). Never run one without the other.",
    stacksWith: ["Ipamorelin"],
  },
  {
    name: "Ipamorelin",
    category: "GH & Muscle",
    strengthUnit: "mg",
    vialSizes: [2, 5, 10],
    defaultBacMl: 2,
    defaultDose: 200,
    defaultDoseUnit: "mcg",
    doseText: "150–300mcg",
    frequency: "2–3x daily, fasted",
    route: "subQ",
    cycle: "8–12 wks, 8 off",
    purpose: "Fat loss / GH",
    solvent: "BAC water",
    notes: "Always pair with a GHRH (CJC-1295).",
    stacksWith: ["CJC-1295 (No DAC)"],
  },
  {
    name: "Tesamorelin",
    category: "GH & Muscle",
    strengthUnit: "mg",
    vialSizes: [10, 20],
    defaultBacMl: 2,
    defaultDose: 1,
    defaultDoseUnit: "mg",
    doseText: "1–2mg",
    frequency: "Daily PM, fasted",
    route: "subQ",
    cycle: "10–16 wks",
    purpose: "Belly fat / LDL / cognitive",
    solvent: "BAC water",
  },
  {
    name: "Sermorelin",
    category: "GH & Muscle",
    strengthUnit: "mg",
    vialSizes: [5, 10],
    defaultBacMl: 2,
    defaultDose: 300,
    defaultDoseUnit: "mcg",
    doseText: "250–500mcg",
    frequency: "Daily PM, fasted",
    route: "subQ",
    cycle: "Up to 6 months",
    purpose: "Muscle / Fat loss / Anti-age / GH / Sleep",
    solvent: "BAC water",
  },
  {
    name: "IGF-1 LR3",
    category: "GH & Muscle",
    strengthUnit: "mg",
    vialSizes: [1],
    defaultBacMl: 2,
    defaultDose: 50,
    defaultDoseUnit: "mcg",
    doseText: "50–100mcg",
    frequency: "AM after workout",
    route: "IM",
    cycle: "10 days – 6 wks",
    purpose: "Muscle growth / recovery / bone",
    solvent: "BAC + Acetic acid",
    notes: "Reconstitute with 1.5ml BAC water + 0.5ml acetic acid.",
    stacksWith: ["CJC-1295 (No DAC)", "Ipamorelin"],
  },
  {
    name: "PEG-MGF",
    category: "GH & Muscle",
    strengthUnit: "mg",
    vialSizes: [2],
    defaultBacMl: 2,
    defaultDose: 100,
    defaultDoseUnit: "mcg",
    doseText: "100mcg each side",
    frequency: "3–4x/week, post-workout",
    route: "IM (bilateral)",
    cycle: "4–8 wks",
    purpose: "Muscle growth / recovery / bone",
    solvent: "BAC water",
  },
  {
    name: "MGF",
    category: "GH & Muscle",
    strengthUnit: "mg",
    vialSizes: [2, 5, 10],
    defaultBacMl: 2,
    defaultDose: 200,
    defaultDoseUnit: "mcg",
    doseText: "200mcg",
    frequency: "Daily post-workout",
    route: "IM (bilateral)",
    cycle: "4–8 wks",
    purpose: "Muscle growth",
    solvent: "BAC water",
  },
  {
    name: "Follistatin 344",
    category: "GH & Muscle",
    strengthUnit: "mg",
    vialSizes: [1],
    defaultBacMl: 2,
    defaultDose: 100,
    defaultDoseUnit: "mcg",
    doseText: "100mcg",
    frequency: "Daily",
    route: "IM (target muscle)",
    cycle: "10–30 days",
    purpose: "Muscle growth",
    solvent: "Acetic acid",
    notes: "Reconstitute with acetic acid, not pure BAC water.",
  },
  {
    name: "GHRP-2",
    category: "GH & Muscle",
    strengthUnit: "mg",
    vialSizes: [5],
    defaultBacMl: 2.5,
    defaultDose: 250,
    defaultDoseUnit: "mcg",
    doseText: "200–250mcg",
    frequency: "2x daily M–F, fasted",
    route: "subQ",
    cycle: "8–12 wks",
    purpose: "GH / fat loss / muscle / sleep / skin",
    solvent: "BAC water",
    notes: "Must pair with a GHRH (CJC-1295).",
    stacksWith: ["CJC-1295 (No DAC)"],
  },
  {
    name: "HGH",
    category: "GH & Muscle",
    strengthUnit: "iu",
    vialSizes: [10, 15, 24, 36],
    defaultBacMl: 1,
    defaultDose: 2,
    defaultDoseUnit: "iu",
    doseText: "1–4 IU",
    frequency: "Daily AM, fasted",
    route: "subQ",
    cycle: "3–6 months",
    purpose: "Muscle / fat / bone / anti-aging",
    solvent: "BAC water",
    notes: "Dosed in IU. Match BAC volume to vial size for easy unit math.",
  },

  // ---------------- FAT LOSS & METABOLISM ----------------
  {
    name: "Retatrutide (Reta)",
    category: "Fat Loss & Metabolism",
    strengthUnit: "mg",
    vialSizes: [10, 15, 20, 30],
    defaultBacMl: 2,
    defaultDose: 2,
    defaultDoseUnit: "mg",
    doseText: "Start 2mg, +1mg/wk when plateaued, max 12mg",
    frequency: "WEEKLY only",
    route: "subQ",
    cycle: "Until results",
    purpose: "Appetite / fat loss / liver / insulin / cholesterol",
    solvent: "BAC water",
    notes: "Triple agonist (GLP-1/GIP/glucagon). WEEKLY injection only — never daily. Titrate slowly.",
    stacksWith: ["Cagrilintide", "5-Amino 1MQ", "AOD-9604"],
  },
  {
    name: "Tirzepatide (Tirz)",
    category: "Fat Loss & Metabolism",
    strengthUnit: "mg",
    vialSizes: [15, 30, 60],
    defaultBacMl: 2,
    defaultDose: 2.5,
    defaultDoseUnit: "mg",
    doseText: "Start 2.5mg, +2.5mg every 4 wks, max 15mg",
    frequency: "WEEKLY only",
    route: "subQ",
    cycle: "Until results",
    purpose: "Weight loss / insulin / cardiovascular",
    solvent: "BAC water",
    notes: "Dual GLP-1/GIP agonist. WEEKLY injection only — never daily.",
  },
  {
    name: "Cagrilintide",
    category: "Fat Loss & Metabolism",
    strengthUnit: "mg",
    vialSizes: [5, 10],
    defaultBacMl: 2,
    defaultDose: 1,
    defaultDoseUnit: "mg",
    doseText: "0.25–2mg",
    frequency: "Weekly or 2x/week",
    route: "subQ",
    cycle: "Up to 16 wks",
    purpose: "Appetite suppression / fat loss",
    solvent: "BAC water",
    notes: "Pairs with GLP-1s.",
    stacksWith: ["Retatrutide (Reta)", "Tirzepatide (Tirz)"],
  },
  {
    name: "AOD-9604",
    category: "Fat Loss & Metabolism",
    strengthUnit: "mg",
    vialSizes: [5],
    defaultBacMl: 2,
    defaultDose: 400,
    defaultDoseUnit: "mcg",
    doseText: "300–500mcg",
    frequency: "Daily AM, fasted",
    route: "subQ",
    cycle: "Ongoing",
    purpose: "Fat loss",
    solvent: "BAC + Acetic acid",
    notes: "Reconstitute with 1.6ml BAC water + 0.4ml acetic acid.",
    stacksWith: ["Ipamorelin", "CJC-1295 (No DAC)", "MOTS-C"],
  },
  {
    name: "5-Amino 1MQ",
    category: "Fat Loss & Metabolism",
    strengthUnit: "mg",
    vialSizes: [10, 50],
    defaultBacMl: 1,
    defaultDose: 25,
    defaultDoseUnit: "mg",
    doseText: "10–50mg",
    frequency: "Daily",
    route: "oral / subQ",
    cycle: "8–12 wks",
    purpose: "NNMT inhibitor / fat loss / NAD+",
    solvent: "BAC water",
    stacksWith: ["Retatrutide (Reta)", "AOD-9604", "MOTS-C"],
  },
  {
    name: "AICAR",
    category: "Fat Loss & Metabolism",
    strengthUnit: "mg",
    vialSizes: [10, 50],
    defaultBacMl: 1,
    defaultDose: 25,
    defaultDoseUnit: "mg",
    doseText: "10–50mg",
    frequency: "Daily",
    route: "subQ",
    cycle: "4–8 wks",
    purpose: "AMPK activator / exercise mimetic",
    solvent: "BAC water",
  },
  {
    name: "MOTS-C",
    category: "Fat Loss & Metabolism",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 1,
    defaultDose: 10,
    defaultDoseUnit: "mg",
    doseText: "5–10mg",
    frequency: "1–3x/week",
    route: "subQ",
    cycle: "8–10 wks",
    purpose: "Performance / insulin / fat loss / mitochondrial",
    solvent: "BAC water",
  },
  {
    name: "SLU-PP-332",
    category: "Fat Loss & Metabolism",
    strengthUnit: "mg",
    vialSizes: [5],
    defaultBacMl: 1,
    defaultDose: 500,
    defaultDoseUnit: "mcg",
    doseText: "500mcg–3mg",
    frequency: "Up to 3x daily",
    route: "subQ",
    cycle: "Ongoing",
    purpose: "Fat loss / energy / recovery / heart",
    solvent: "DMSO / Saline",
    notes: "May need DMSO/Saline to reconstitute.",
  },
  {
    name: "L-Carnitine",
    category: "Fat Loss & Metabolism",
    strengthUnit: "mg",
    vialSizes: [500, 600],
    defaultBacMl: 0,
    defaultDose: 400,
    defaultDoseUnit: "mg",
    doseText: "250–600mg",
    frequency: "Daily as needed",
    route: "IM",
    cycle: "Months",
    purpose: "Body composition / energy / fat loss",
    solvent: "Pre-mixed",
    notes: "Pre-mixed solution — no reconstitution needed (500–600 mg/ml).",
  },

  // ---------------- HEALING & RECOVERY ----------------
  {
    name: "BPC-157",
    category: "Healing & Recovery",
    strengthUnit: "mg",
    vialSizes: [5, 10],
    defaultBacMl: 2,
    defaultDose: 250,
    defaultDoseUnit: "mcg",
    doseText: "250–500mcg (up to 1000mcg/day)",
    frequency: "2–3x daily",
    route: "subQ / IM",
    cycle: "8 wks on, 8 off",
    purpose: "Tissue repair, near injury site",
    solvent: "BAC water",
    notes: "Healing peptide only — NOT for fat loss.",
    stacksWith: ["TB-500", "GHK-Cu"],
  },
  {
    name: "TB-500",
    category: "Healing & Recovery",
    strengthUnit: "mg",
    vialSizes: [5, 10],
    defaultBacMl: 3,
    defaultDose: 500,
    defaultDoseUnit: "mcg",
    doseText: "500–1000mcg (2–2.5mg 2x/wk loading)",
    frequency: "Daily",
    route: "subQ",
    cycle: "8 wks on, 8 off",
    purpose: "Systemic healing, recovery",
    solvent: "BAC water",
    notes: "Healing peptide only — NOT for fat loss.",
    stacksWith: ["BPC-157", "GHK-Cu"],
  },
  {
    name: "BPC/TB-500 Blend",
    category: "Healing & Recovery",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 2,
    defaultDose: 250,
    defaultDoseUnit: "mcg",
    doseText: "250mcg each",
    frequency: "2–3x daily",
    route: "subQ",
    cycle: "8 wks on, 8 off",
    purpose: "Gold-standard healing combo",
    solvent: "BAC water",
    blend: true,
    notes: "5mg BPC-157 + 5mg TB-500 (10mg total).",
  },
  {
    name: "GHK-Cu / AHK-Cu",
    category: "Healing & Recovery",
    strengthUnit: "mg",
    vialSizes: [100],
    defaultBacMl: 3,
    defaultDose: 2.5,
    defaultDoseUnit: "mg",
    doseText: "2.5mg (up to 5mg)",
    frequency: "Daily",
    route: "subQ / topical",
    cycle: "8 wks on, 8 off",
    purpose: "Healing / skin / hair / anti-inflammatory",
    solvent: "BAC water",
  },
  {
    name: "GLOW (BPC / TB / GHK-Cu)",
    category: "Healing & Recovery",
    strengthUnit: "mg",
    vialSizes: [90],
    defaultBacMl: 3,
    defaultDose: 4.5,
    defaultDoseUnit: "mg",
    doseText: "500 / 500 / 3500 mcg",
    frequency: "Daily",
    route: "subQ",
    cycle: "8 wks on, 8 off",
    purpose: "Healing + skin/hair blend",
    solvent: "BAC water",
    blend: true,
    notes: "10mg BPC + 10mg TB-500 + 70mg GHK-Cu (90mg total). Don't dose higher.",
  },
  {
    name: "KLOW (BPC / TB / GHK-Cu / KPV)",
    category: "Healing & Recovery",
    strengthUnit: "mg",
    vialSizes: [80],
    defaultBacMl: 3,
    defaultDose: 4,
    defaultDoseUnit: "mg",
    doseText: "500 / 500 mcg / 2.5mg / 500mcg",
    frequency: "Daily",
    route: "subQ",
    cycle: "8 wks on, 8 off",
    purpose: "Healing + anti-inflammatory blend",
    solvent: "BAC water",
    blend: true,
    notes: "10mg BPC + 10mg TB + 50mg GHK-Cu + 10mg KPV (80mg total). Don't dose higher.",
  },
  {
    name: "KPV",
    category: "Healing & Recovery",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 2,
    defaultDose: 500,
    defaultDoseUnit: "mcg",
    doseText: "500mcg–1mg",
    frequency: "M–F",
    route: "subQ / oral",
    cycle: "8 wks on, 8 off",
    purpose: "Anti-inflammatory / gut",
    solvent: "BAC water",
    notes: "Avoid NSAIDs while running.",
  },
  {
    name: "Deadpool (Cartalax / BPC / TB)",
    category: "Healing & Recovery",
    strengthUnit: "mg",
    vialSizes: [20],
    defaultBacMl: 2,
    defaultDose: 2,
    defaultDoseUnit: "mg",
    doseText: "2mg (20 units)",
    frequency: "Daily",
    route: "subQ (near injury)",
    cycle: "30 days, 2–3x/year",
    purpose: "Joint / cartilage / tissue repair",
    solvent: "BAC water",
    blend: true,
    notes: "P4P blend: Cartalax 10mg + BPC-157 5mg + TB-500 5mg (20mg total).",
  },
  {
    name: "Abaloparatide",
    category: "Healing & Recovery",
    strengthUnit: "mg",
    vialSizes: [3.12],
    defaultBacMl: 0,
    defaultDose: 80,
    defaultDoseUnit: "mcg",
    doseText: "80mcg",
    frequency: "Daily",
    route: "subQ",
    cycle: "18 months max",
    purpose: "Bone density (FDA approved)",
    solvent: "Pre-mixed",
  },

  // ---------------- LONGEVITY & MITOCHONDRIAL ----------------
  {
    name: "FOXO4-DRI",
    category: "Longevity & Mitochondrial",
    strengthUnit: "mg",
    vialSizes: [5, 10],
    defaultBacMl: 1,
    defaultDose: 4,
    defaultDoseUnit: "mg",
    doseText: "3–5mg (EOD) or 1mg (5 on / 5 off)",
    frequency: "Every other day",
    route: "subQ",
    cycle: "Ongoing / 2 wks 2x/year",
    purpose: "Senolytic — clears weak cells / anti-aging",
    solvent: "BAC water",
  },
  {
    name: "Epitalon",
    category: "Longevity & Mitochondrial",
    strengthUnit: "mg",
    vialSizes: [10, 50],
    defaultBacMl: 1,
    defaultDose: 5,
    defaultDoseUnit: "mg",
    doseText: "5–10mg",
    frequency: "Daily PM",
    route: "subQ / IV",
    cycle: "10–20 days, 1–2x/year",
    purpose: "Telomeres / anti-aging / sleep / immune",
    solvent: "BAC water",
    stacksWith: ["Vilon", "Livagen"],
  },
  {
    name: "SS-31",
    category: "Longevity & Mitochondrial",
    strengthUnit: "mg",
    vialSizes: [10, 30, 50],
    defaultBacMl: 2,
    defaultDose: 1,
    defaultDoseUnit: "mg",
    doseText: "1–3mg (0.1–0.5mg/kg/day)",
    frequency: "Daily",
    route: "subQ",
    cycle: "8–12 wks",
    purpose: "Mitochondrial / cardioprotection / energy",
    solvent: "BAC water",
  },
  {
    name: "NAD+ (Buffered)",
    category: "Longevity & Mitochondrial",
    strengthUnit: "mg",
    vialSizes: [500],
    defaultBacMl: 2,
    defaultDose: 250,
    defaultDoseUnit: "mg",
    doseText: "250–500mg",
    frequency: "Daily or as needed",
    route: "IV / subQ",
    cycle: "Ongoing",
    purpose: "Cellular energy / DNA repair / anti-aging",
    solvent: "BAC water",
  },
  {
    name: "Humanin",
    category: "Longevity & Mitochondrial",
    strengthUnit: "mg",
    vialSizes: [5],
    defaultBacMl: 1,
    defaultDose: 1,
    defaultDoseUnit: "mg",
    doseText: "1–2mg",
    frequency: "Daily",
    route: "subQ",
    cycle: "4–8 wks",
    purpose: "Cardioprotection / neuroprotection",
    solvent: "BAC water",
  },
  {
    name: "MitoPrime",
    category: "Longevity & Mitochondrial",
    strengthUnit: "mg",
    vialSizes: [25],
    defaultBacMl: 0,
    defaultDose: 15,
    defaultDoseUnit: "mg",
    doseText: "5–25mg oral",
    frequency: "Daily",
    route: "oral",
    cycle: "Ongoing",
    purpose: "Mitochondrial antioxidant",
    solvent: "None (oral)",
  },

  // ---------------- COGNITIVE & MOOD ----------------
  {
    name: "Semax",
    category: "Cognitive & Mood",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 3,
    defaultDose: 300,
    defaultDoseUnit: "mcg",
    doseText: "200–330mcg (200–600mcg intranasal)",
    frequency: "Daily AM (1–2x)",
    route: "intranasal / subQ",
    cycle: "8 wks on, 8 off",
    purpose: "Cognitive / memory / neuroprotection",
    solvent: "BAC water",
    stacksWith: ["Selank"],
  },
  {
    name: "Selank",
    category: "Cognitive & Mood",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 3,
    defaultDose: 300,
    defaultDoseUnit: "mcg",
    doseText: "200–330mcg (250–500mcg)",
    frequency: "Daily AM (1–3x)",
    route: "intranasal / subQ",
    cycle: "8 wks on, 8 off",
    purpose: "Anxiety / cognitive / memory / mood",
    solvent: "BAC water",
    stacksWith: ["Semax"],
  },
  {
    name: "PE-22-28",
    category: "Cognitive & Mood",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 2,
    defaultDose: 500,
    defaultDoseUnit: "mcg",
    doseText: "250mcg–1mg",
    frequency: "Daily",
    route: "subQ",
    cycle: "8–12 wks",
    purpose: "Cognitive / antidepressant / focus",
    solvent: "BAC water",
  },
  {
    name: "Cerebrolysin",
    category: "Cognitive & Mood",
    strengthUnit: "mg",
    vialSizes: [30],
    defaultBacMl: 2,
    defaultDose: 3,
    defaultDoseUnit: "mg",
    doseText: "2–5mg (5–10ml)",
    frequency: "Daily / 5x per week",
    route: "IV / IM",
    cycle: "4–6 wks",
    purpose: "Neuroregeneration / cognitive",
    solvent: "Pre-mixed",
  },
  {
    name: "VIP",
    category: "Cognitive & Mood",
    strengthUnit: "mg",
    vialSizes: [5],
    defaultBacMl: 3,
    defaultDose: 200,
    defaultDoseUnit: "mcg",
    doseText: "100–300mcg",
    frequency: "Daily",
    route: "intranasal / subQ",
    cycle: "8 wks on, 8 off",
    purpose: "Memory / autoimmune / blood flow",
    solvent: "BAC water",
  },
  {
    name: "DSIP",
    category: "Cognitive & Mood",
    strengthUnit: "mg",
    vialSizes: [5],
    defaultBacMl: 2,
    defaultDose: 250,
    defaultDoseUnit: "mcg",
    doseText: "250–500mcg",
    frequency: "Daily PM",
    route: "subQ",
    cycle: "8 wks on, 8 off",
    purpose: "Sleep (1–3 hrs before bed)",
    solvent: "BAC water",
  },

  // ---------------- IMMUNITY & INFLAMMATION ----------------
  {
    name: "Thymosin Alpha-1",
    category: "Immunity & Inflammation",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 2,
    defaultDose: 1,
    defaultDoseUnit: "mg",
    doseText: "500mcg–1mg (1.6mg 2x/wk)",
    frequency: "2x weekly",
    route: "subQ",
    cycle: "8–12 wks",
    purpose: "Immunity / anti-viral / anti-bacterial",
    solvent: "BAC water",
    stacksWith: ["Glutathione"],
  },
  {
    name: "Thymalin",
    category: "Immunity & Inflammation",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 1,
    defaultDose: 10,
    defaultDoseUnit: "mg",
    doseText: "10mg",
    frequency: "Daily",
    route: "subQ",
    cycle: "10 days, 1–4x/year",
    purpose: "Immunity",
    solvent: "BAC water",
  },
  {
    name: "LL-37",
    category: "Immunity & Inflammation",
    strengthUnit: "mg",
    vialSizes: [5],
    defaultBacMl: 3,
    defaultDose: 150,
    defaultDoseUnit: "mcg",
    doseText: "150mcg",
    frequency: "2x daily AM/PM",
    route: "subQ",
    cycle: "50 days",
    purpose: "Immunity / anti-inflammation",
    solvent: "BAC water",
  },
  {
    name: "Glutathione",
    category: "Immunity & Inflammation",
    strengthUnit: "mg",
    vialSizes: [600, 1500],
    defaultBacMl: 3,
    defaultDose: 1500,
    defaultDoseUnit: "mg",
    doseText: "600–1500mg",
    frequency: "2–3x/week",
    route: "IV / subQ",
    cycle: "Ongoing",
    purpose: "Antioxidant / immune / liver / skin",
    solvent: "BAC water",
    stacksWith: ["Thymosin Alpha-1"],
  },
  {
    name: "KPV (immune)",
    category: "Immunity & Inflammation",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 2,
    defaultDose: 500,
    defaultDoseUnit: "mcg",
    doseText: "500mcg/day",
    frequency: "Daily",
    route: "subQ / oral",
    cycle: "4–8 wks",
    purpose: "Anti-inflammatory / immune / gut",
    solvent: "BAC water",
  },

  // ---------------- HAIR, SKIN & COSMETIC ----------------
  {
    name: "SNAP-8",
    category: "Hair, Skin & Cosmetic",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 2,
    defaultDose: 500,
    defaultDoseUnit: "mcg",
    doseText: "500mcg–1mg",
    frequency: "Daily",
    route: "topical / subQ",
    cycle: "8 wks on, 8 off",
    purpose: "Anti-wrinkle",
    solvent: "BAC water",
  },
  {
    name: "Melanotan I",
    category: "Hair, Skin & Cosmetic",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 2,
    defaultDose: 500,
    defaultDoseUnit: "mcg",
    doseText: "500mcg",
    frequency: "2–3x weekly",
    route: "subQ",
    cycle: "30 days",
    purpose: "Tanning / UV protection",
    solvent: "BAC water",
  },
  {
    name: "PTD-BDM",
    category: "Hair, Skin & Cosmetic",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 2,
    defaultDose: 500,
    defaultDoseUnit: "mcg",
    doseText: "500mcg–1mg",
    frequency: "Daily",
    route: "topical / subQ",
    cycle: "12–24 wks",
    purpose: "Hair growth (hair loss only)",
    solvent: "BAC water",
    notes: "Hair growth peptide only — NOT for fat loss.",
  },

  // ---------------- SEXUAL HEALTH ----------------
  {
    name: "PT-141 (Bremelanotide)",
    category: "Sexual Health",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 2,
    defaultDose: 1,
    defaultDoseUnit: "mg",
    doseText: "0.5–2mg (45–60 min before)",
    frequency: "As needed",
    route: "subQ",
    cycle: "As needed",
    purpose: "Libido (men and women)",
    solvent: "BAC water",
    notes: "Start low.",
  },
  {
    name: "Kisspeptin",
    category: "Sexual Health",
    strengthUnit: "mg",
    vialSizes: [10],
    defaultBacMl: 2,
    defaultDose: 200,
    defaultDoseUnit: "mcg",
    doseText: "100–300mcg",
    frequency: "Daily",
    route: "subQ",
    cycle: "4–8 wks",
    purpose: "Libido / mood / hormonal",
    solvent: "BAC + Acetic acid",
    notes: "May need a small amount of acetic acid to prevent gelling.",
  },
  {
    name: "HCG",
    category: "Sexual Health",
    strengthUnit: "iu",
    vialSizes: [5000],
    defaultBacMl: 1,
    defaultDose: 500,
    defaultDoseUnit: "iu",
    doseText: "500–1000 IU",
    frequency: "3x/week",
    route: "subQ",
    cycle: "As needed / PCT",
    purpose: "LH mimetic / testosterone / fertility",
    solvent: "BAC water",
    notes: "Reconstitute 5000iu vial with 1ml BAC water → 10 units = 500 IU, 20 units = 1000 IU.",
  },

  // ---------------- BIOREGULATORS ----------------
  ...(
    [
      ["Vilon", "Neuroprotective", "Mood / focus — dose 5–10mg/day. Pair with Epitalon.", 5, 10],
      ["Cardiogen", "Heart", "Heart cell growth, reduce scars, anti-tumor.", 3, 3],
      ["Bronchagen", "Lungs", "Lung function, inflammation, DNA stabilization, asthma.", 3, 3],
      ["Prostamax", "Prostate", "Prostate support, anti-inflammatory, PCT.", 3, 3],
      ["Testagen", "Pituitary / Testosterone", "Testosterone, energy, cognitive.", 3, 3],
      ["Ovagen", "Liver", "Liver inflammation, metabolic function.", 3, 3],
      ["Cartalax", "Joints / Cartilage", "Joint/cartilage regeneration, inflammation.", 3, 3],
      ["Chronluten", "Lungs", "Lung health (use with Bronchagen).", 3, 3],
      ["Vesugen", "Cognitive / Nerve", "Cognitive/nerve health, anabolic, anti-aging.", 3, 3],
      ["Livagen", "Cellular", "Cellular regeneration, immune system.", 3, 3],
      ["Cortagen", "Pancreas", "Pancreatic cell repair.", 3, 3],
      ["Pancragen", "Immunity", "Immunity, viral/bacterial protection.", 3, 3],
      ["Thymogen", "Immunity", "Immunity — IM injection only.", 3, 3],
      ["Crystagen", "General Wellness", "Immunity, protein synthesis, recovery.", 3, 3],
    ] as const
  ).map(
    ([name, organ, purpose, dose, defVial]): Peptide => ({
      name,
      category: "Bioregulators",
      strengthUnit: "mg",
      vialSizes: [defVial, 20],
      defaultBacMl: 2,
      defaultDose: dose,
      defaultDoseUnit: "mg",
      doseText: name === "Vilon" ? "5–10mg/day" : "2–4mg/day",
      frequency: "Daily",
      route: name === "Thymogen" ? "IM only" : "subQ",
      cycle: "30 days, 2–3x/year",
      purpose: `${organ} — ${purpose}`,
      solvent: "BAC water",
    }),
  ),
];

/** Popular ready-made stacks from the master document. */
export interface Stack {
  name: string;
  level?: string;
  goal: string;
  items: string[];
}

export const STACKS: Stack[] = [
  {
    name: "Fat Loss",
    level: "Beginner",
    goal: "Fat Loss & Metabolism",
    items: [
      "Reta 10mg — 2mg/week subQ, increase slowly",
      "AOD-9604 5mg — 300mcg/day AM fasted",
      "CJC-1295 / Ipamorelin — 200mcg each 2x daily",
    ],
  },
  {
    name: "Fat Loss",
    level: "Advanced",
    goal: "Fat Loss & Metabolism",
    items: [
      "Reta 15–20mg — 4–8mg/week",
      "Cagrilintide — 1mg/week (pairs with GLP-1)",
      "5-Amino 1MQ — 25mg/day",
      "MOTS-C — 10mg 3x/week",
    ],
  },
  {
    name: "Healing",
    goal: "Healing & Recovery",
    items: [
      "BPC-157 5mg — 250mcg 2x daily near injury",
      "TB-500 5mg — 2mg 2x/week loading",
      "GHK-Cu — 2mg/day",
    ],
  },
  {
    name: "GH / Muscle",
    goal: "GH & Muscle",
    items: [
      "CJC-1295 No DAC 5mg — 200mcg 3x daily fasted",
      "Ipamorelin 5mg — 200mcg 3x daily fasted",
      "IGF-1 LR3 — 50mcg post-workout (advanced)",
    ],
  },
  {
    name: "Anti-Aging / Longevity",
    goal: "Longevity & Mitochondrial",
    items: [
      "Epitalon 10mg — 10mg/day, 20 days, 2x/year",
      "Vilon 20mg — 5–10mg/day, 30 days",
      "SS-31 30mg — 1mg/day",
      "NAD+ 500mg — 250mg 3x/week",
      "MOTS-C 10mg — 10mg 3x/week",
    ],
  },
  {
    name: "Cognitive",
    goal: "Cognitive & Mood",
    items: [
      "Semax 10mg — 300mcg intranasal AM",
      "Selank 10mg — 300mcg intranasal AM",
      "NAD+ — 250mg 3x/week",
    ],
  },
  {
    name: "Immune",
    goal: "Immunity & Inflammation",
    items: [
      "Thymosin Alpha-1 10mg — 1mg 2x/week",
      "Glutathione 1500mg — 1500mg 2x/week",
      "KPV 10mg — 500mcg/day",
    ],
  },
];

/** Stacking & safety rules from the master document. */
export const RULES: string[] = [
  "Never run more than 4–5 peptides per protocol — more is not better.",
  "GHRPs (Ipamorelin, GHRP-2) must always be paired with a GHRH (CJC-1295).",
  "BPC-157 + TB-500 is the gold-standard healing combo.",
  "Epitalon + Vilon is the go-to longevity combo.",
  "GLP-1s (Reta / Tirz) are WEEKLY injections only — never daily. Start low and titrate slowly.",
  "Never use BPC-157 or TB-500 for fat loss — they are healing peptides only.",
  "Never use PTD-BDM for fat loss — it is a hair-growth peptide.",
  "Bioregulators are organ-specific — match them to the client's specific organ/system.",
  "AOD-9604, IGF-1 LR3, Follistatin 344 and Kisspeptin need acetic acid, not pure BAC water.",
];

/** Reconstitution reference notes from the master document. */
export const RECON_NOTES: string[] = [
  "Standard formula: BAC water volume ÷ vial size = concentration per ml.",
  "1 ml = 100 units on a standard U-100 insulin syringe.",
  "5mg vial + 2ml BAC water = 2.5mg/ml = 250mcg per 10 units.",
  "10mg vial + 2ml BAC water = 5mg/ml = 500mcg per 10 units.",
  "10mg vial + 3ml BAC water = 3.33mg/ml = 333mcg per 10 units.",
  "BAC water preserves reconstituted peptides ~30–60 days refrigerated.",
  "Acetic acid (0.6%) is only for peptides that gel or precipitate in BAC water.",
];
